### ISSUE TITLE
I saw you are trying to interface JSBSim into Julia ...

### ISSUE THREAD

**Issue by abassign** [JSBSim-Team/JSBSim.jl#2]
I'm working on it too, right now I'm learning to use it and I have produced this tool for FGFS:
https://forum.flightgear.org/viewtopic.php?f=5&t=39066&sid=e195f64a4463d5acba53e01f931901a6
It's definitely very experimental ... but it's just to tell you that something could be done with Julia ... My idea is this:
JSBSim has an excellent interface with FGFS ... Julia does not have interfaces with FGFS recognized by the FGFS community (they are rather conservative) now if I could combine Julia modules in JSBSim I could do two things: Enrich JSBSim functions maybe specialized functions for certain types of airplane ... and being able to access efficiently with the FGFS property-tree .. maybe what I tell you is absurd, but given what you can do with Julia, I honestly think that interesting things could come.
Greetings
Adriano

**Comment by bcoconni** [comment]
Your project seems interesting however I struggle to see the connexion with JSBSim.jl which is merely a Julia binding for JSBSim. At its core, JSBSim.jl is still using the C++ code that is hosted in [JSBSim-Team/JSBSim](https://github.com/JSBSim-Team/jsbsim): the very same code that FlightGear uses.

However if JSBSim.jl will help you in your project at some point then I will be glad to hear about it.

I'll close this issue because this discussion is not related to the project.
